### ISSUE TITLE
transaction

### ISSUE THREAD

**Issue by vitaly-sazonov** [Unbuttun/fastify-slonik#24]
Hi.

Why is the transaction function implemented as a wrapper around pool.query?

**Comment by spa5k** [comment]
hey @VitalySazonov , sorry i somehow skipped this issue, but after you mentioned it, i have directly removed the transaction from the slonik.transaction since it was wrong using query for it.

now you can access it by doing `this.pool.transaction`, more info on https://github.com/spa5k/fastify-slonik/pull/59, it can be access from updating fastify-slonik to latest version
