### ISSUE TITLE
`this.slonik` is a type error

### ISSUE THREAD

**Issue by frysztak** [Unbuttun/fastify-slonik#86]
Perhaps I'm missing something, but it seems like this plugin doesn't extend `fastify` types? Currently `this.slonik` is a type error. TS has this neat feature called declaration merging, which Fastify docs mention [here](https://www.fastify.io/docs/latest/Reference/TypeScript/#creating-a-typescript-fastify-plugin)

**Comment by spa5k** [comment]
Thanks for informing me, I'll check and see what went wrong.

**Comment by spa5k** [comment]
hey @frysztak you can prevent such error by appending this before the request - 
```ts
fastify.get('/users', async function (this, request, reply) {

  const queryText = this.sql`
    SELECT * FROM users WHERE user_id = 1
  `
}
```
in order to escape the error.

Also in latest version, i've added better interface support, although they were working before, but it seemed like it wasn't working on yours setup, so the declaration merging is more explicilty done. In addition if you are using arrow functions, you can get slonik and sql decoration from request.slonik etc, more into README.md file.

**Comment by spa5k** [comment]
I'll be closing it off then.

**Comment by frysztak** [comment]
I haven't had the chance to check it out yet, but thanks a lot! :rocket:
